Document: libbuddy
Title: Debian libbuddy Manual
Author: <insert document author here>
Abstract: This manual describes what libbuddy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbuddy/libbuddy.sgml.gz

Format: postscript
Files: /usr/share/doc/libbuddy/libbuddy.ps.gz

Format: text
Files: /usr/share/doc/libbuddy/libbuddy.text.gz

Format: HTML
Index: /usr/share/doc/libbuddy/html/index.html
Files: /usr/share/doc/libbuddy/html/*.html
